version: "3.8"
services:
  mongodb:
    image: 'mongo'
    ports:
      - 27017:27017
  backend:
    build: ./backend
    ports:
      - 5000:5000
    # exponse: 8080/8080
    volumes:
      - ./backend:/index
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/index
    stdin_open: true
    tty: true
    depends_on:
      - backend
